# .github/workflows/release.yml
name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger the workflow only on tag pushes (e.g., v1.0.0)

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build binary with PyInstaller
        run: |
          pyinstaller --onefile student_log_script.py
        shell: bash

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-binary
          path: dist/student_log_script*  # Adjust the filename as per the OS

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download binaries from build jobs
        uses: actions/download-artifact@v3
        with:
          name: ubuntu-latest-binary
          path: ./dist/ubuntu

      - name: Download macOS binary
        uses: actions/download-artifact@v3
        with:
          name: macos-latest-binary
          path: ./dist/macos

      - name: Download Windows binary
        uses: actions/download-artifact@v3
        with:
          name: windows-latest-binary
          path: ./dist/windows

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./dist/ubuntu/student_log_script
            ./dist/macos/student_log_script
            ./dist/windows/student_log_script.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
