name: Build and Release Binaries

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create dist directories if not exist
        run: |
          mkdir -p dist
        shell: bash

      - name: Build binary with PyInstaller
        run: |
          if [[ "${{ matrix.os }}" == 'ubuntu-latest' ]]; then
            pyinstaller --onefile student_log_script.py --name ubuntu_student_log_script
            ls -lhaR dist/
          elif [[ "${{ matrix.os }}" == 'macos-13' ]]; then
            pyinstaller --onefile student_log_script.py --name macos_student_log_script
            ls -lhaR dist/
          elif [[ "${{ matrix.os }}" == 'macos-latest' ]]; then
            pyinstaller --onefile student_log_script.py --name macos_m1_student_log_script
            ls -lhaR dist/
          elif [[ "${{ matrix.os }}" == 'windows-latest' ]]; then
            pyinstaller --onefile student_log_script.py --name student_log_script.exe
            ls -R dist/
          fi
        shell: bash

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: latest-binary
          path: |
            dist/ubuntu_student_log_script
            dist/macos_student_log_script
            dist/macos_m1_student_log_script
            dist/student_log_script.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Create dist directories for release
        run: mkdir -p dist

      - name: Download binaries from build jobs
        uses: actions/download-artifact@v3
        with:
          name: latest-binary
          path: dist

      - name: List dist folder contents (debug step)
        run: ls -lhaR dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/ubuntu_student_log_script
            dist/macos_student_log_script
            dist/macos_m1_student_log_script
            dist/student_log_script.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
